name: SonarQube Analysis
on: [push]
jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Run SonarQube script
        run: |
          chmod +x .github/scripts/run_sonarqube.sh
          TOKEN=$(.github/scripts/run_sonarqube.sh)
          echo $TOKEN
          sonar_token=$(echo "$TOKEN" | tail -n 1)
          echo "SONAR_TOKEN=$sonar_token" >> $GITHUB_ENV
          Docker_IP=$(docker container inspect -f '{{ .NetworkSettings.IPAddress }}' sonarqube)
          url="http://$Docker_IP:9000"
          echo $url
          echo "SONAR_URL=$url" >> $GITHUB_ENV
        id: run-script

      - name: Build with Maven
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_URL }}
        run: |
          cd $GITHUB_WORKSPACE/my-app
          mvn -B clean verify --file pom.xml
          mvn sonar:sonar

      # - name: Run SonarQube Scanner
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ env.SONAR_URL }}
      #   with:
      #     projectBaseDir: ./my-app

      # - name: Run SonarQube scan
      #   env:
      #     SONAR_TOKEN: ${{ steps.run-script.outputs.sonar_token }}
      #   run: |
      #     cd ./my-app
      #     sonar-scanner \
      #       -Dsonar.host.url=http://localhost:9000 \
      #       -Dsonar.login=$SONAR_TOKEN
