name: SonarQube Analysis
on: [push]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: |
          cd $GITHUB_WORKSPACE/my-app
          mvn -B clean verify --file pom.xml

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Run SonarQube script
        run: |
          set -x
          bash .github/scripts/run_sonarqube.sh
          echo "sonar_token=$USER_TOKEN" >> $GITHUB_OUTPUT
        id: run-script

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./my-app
          args: >
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=${{ steps.run-script.outputs.sonar_token }}

      - name: Run SonarQube scan
        run: sonar-scanner
