name: SonarQube Analysis
on: [push]
jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: |
          cd $GITHUB_WORKSPACE/my-app
          mvn -B clean verify --file pom.xml

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Run SonarQube script
        run: |
          chmod +x .github/scripts/run_sonarqube.sh
          TOKEN=$(.github/scripts/run_sonarqube.sh)
          echo $TOKEN
          sonar_token=$(echo "$TOKEN" | tail -n 1)
          echo "SONAR_TOKEN=$sonar_token" >> $GITHUB_ENV
        id: run-script

      - name: evaluvate output of Run SonarQube script
        run: |
          echo ${{ steps.run-script.outputs.sonar_token }}
          docker ps

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"
        with:
          projectBaseDir: ./my-app

      - name: Run SonarQube scan
        env:
          SONAR_TOKEN: ${{ steps.run-script.outputs.sonar_token }}
        run: |
          cd ./my-app
          sonar-scanner \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN
